fix 10336: Captcha: Incorrect error message if context parameters are not set
primefaces/primefaces pull request #10337
Opened 2023-07-12 14:16 UTC by bvfalcon

FIX for [#10336](https://github.com/primefaces/primefaces/issues/10336)

2023-07-12 14:30 UTC, melloware requested changes

2023-07-12 14:30 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/captcha/Captcha.java
> +        String privateKey = context.getExternalContext().getInitParameter(Captcha.PRIVATE_KEY);
You still need the other step though second `context.getApplication().evaluateExpressionGet` because if someone uses an EL Expression like...

```xml
<context-param>
    <param-name>primefaces.PRIVATE_CAPTCHA_KEY</param-name>
    <param-value>#{yourBean.privateKey}</param-value>
</context-param>
```

2023-07-12 15:15 UTC, bvfalcon commented on primefaces/src/main/java/org/primefaces/component/captcha/Captcha.java
> +        String privateKey = context.getExternalContext().getInitParameter(Captcha.PRIVATE_KEY);
Thanks for explanation. Reading showcase, this moment is not obvious. I add change to PR: context-param value will be processed as EL-expression. Only as fallback-strategy source value will be used

2023-07-12 19:53 UTC, melloware requested changes

2023-07-12 19:53 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/captcha/Captcha.java
> +            LOGGER.fine(() -> "Error to process context parameter " + Captcha.PRIVATE_KEY + " as EL-expression: " + e.getMessage());
```suggestion
            LOGGER.fine(() -> "Error processing context parameter " + Captcha.PRIVATE_KEY + " as EL-expression: " + e.getMessage());
```

2023-07-12 19:53 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java
> +            LOGGER.fine(() -> "Error to process context parameter " + Captcha.PUBLIC_KEY + " as EL-expression: " + e.getMessage());
```suggestion
            LOGGER.fine(() -> "Error processing context parameter " + Captcha.PUBLIC_KEY + " as EL-expression: " + e.getMessage());
```

2023-07-13 07:18 UTC, tandraschko commented on primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java
> +        if (publicKey == null) {
just cosmetics, i like this more:

if (publicKey != null) {
   do some elStuff
}

return publicKey;

2023-07-13 07:54 UTC, tandraschko commented
you have some checkstyle violations

2023-07-13 08:50 UTC, merged