AutoComplete-add-separator-to-style-itemLabel
primefaces/primefaces pull request #10491
Opened 2023-08-14 16:28 UTC by nimo23

Fixes https://github.com/primefaces/primefaces/issues/10489.

2023-08-14 16:40 UTC, melloware requested changes

2023-08-14 16:40 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +                if (itemLabelEscaped.includes(separator)) {
```suggestion
                if (separator && itemLabelEscaped.includes(separator)) {
```

2023-08-14 16:40 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +                itemDisplayMarkup += '<span class="ui-autocomplete-token-label">' + (itemLabelHtml || itemLabelEscaped) + '</span></li>';
I think we need Integration tests added proving this case works.

2023-08-14 16:49 UTC, nimo23 commented on primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +                itemDisplayMarkup += '<span class="ui-autocomplete-token-label">' + (itemLabelHtml || itemLabelEscaped) + '</span></li>';
I don't know how to do integration tests. But I can also use the following version which would elminate the need of the integration test, or?:

```
 itemDisplayMarkup += '<span class="ui-autocomplete-token-label">' + (itemLabelHtml == null ? itemLabelEscaped : itemLabelHtml) + '</span></li>';
```

2023-08-15 08:48 UTC, nimo23 commented on primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +                itemDisplayMarkup += '<span class="ui-autocomplete-token-label">' + (itemLabelHtml || itemLabelEscaped) + '</span></li>';
I changed the code which does not need an integration test:

`itemDisplayMarkup += '<span class="ui-autocomplete-token-label">' + (itemLabelHtml == null ? itemLabelEscaped : itemLabelHtml) + '</span></li>';`

2023-08-21 13:45 UTC, tandraschko commented
see my last comment in the issue

2023-08-21 13:45 UTC, closed without merging