Fix #10918: Column(s) filterPlaceholder property
primefaces/primefaces pull request #10927
Opened 2023-10-27 18:24 UTC by melloware

Fix #10918: Column(s) filterPlaceholder property

Makes it consistent with the other 3 prime libraries.

2023-10-27 18:53 UTC, FlipWarthog approved these changes

2023-10-27 21:57 UTC, Rapster commented on primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
> +            if (column.getFilterPlaceholder() != null) {
`LangUtils#isNotBlank`

2023-10-27 21:57 UTC, Rapster requested changes
LangUtils#isNotBlank

2023-10-28 11:48 UTC, melloware commented
Thanks @Rapster i switched to LangUtils.isNotBlank.

2023-10-28 15:44 UTC, merged