Update primefaces.taglib.xml -> fix description
primefaces/primefaces pull request #12042
Opened 2024-05-31 15:29 UTC by Del-Tab

the description was previously changed from `values are new (default), add none.` to `values are new (default), and none.` but add is a valid value

2024-05-31 15:37 UTC, melloware requested changes

2024-05-31 15:37 UTC, melloware commented on primefaces/src/main/resources/META-INF/primefaces.taglib.xml
> +                <![CDATA[Defines row select mode for checkbox based selection, valid values are new (default, sets the line
```suggestion
                <![CDATA[Defines row select mode for checkbox based selection, valid values are 'new' (default, sets the line
```

2024-05-31 15:37 UTC, melloware commented on primefaces/src/main/resources/META-INF/primefaces.taglib.xml
> +                as the only selected line), add (adds to selection) and none (the selection is untouched).]]>
```suggestion
                as the only selected line), 'add' (adds to selection) and 'none' (the selection is untouched).]]>
```

2024-05-31 15:41 UTC, Del-Tab commented on primefaces/src/main/resources/META-INF/primefaces.taglib.xml
> +                <![CDATA[Defines row select mode for checkbox based selection, valid values are new (default, sets the line
thanks, also 'add' toggles the line, it doesn't 'add'

2024-05-31 15:45 UTC, melloware approved these changes

2024-05-31 15:54 UTC, melloware commented
Assigned to @Rapster so he can verify your descriptions.

2024-05-31 17:28 UTC, Rapster commented on docs/14_0_0/components/datatable.md
> +| selectionRowMode          | new                | String           | Defines row select mode for checkbox based selection, valid values are 'new' (default, sets the line as the only selected line),
I don't remember well how this option works... what do you mean by it 'toggles' the selection? If that's what it is, why did we call it 'add' ?

2024-06-15 19:58 UTC, Rapster commented on docs/14_0_0/components/datatable.md
> +| selectionRowMode          | new                | String           | Defines row select mode for checkbox based selection, valid values are 'new' (default, sets the line as the only selected line),
That's what I see from the js doc:

```
* @typedef {"new" | "add" | "none"} PrimeFaces.widget.DataTable.SelectionRowMode Indicates how rows of a DataTable
 * may be selected, when clicking on the row itself (not the checkbox / radiobutton from p:column).
 * `new` always unselects other rows, `add` preserves the currently selected rows, and `none` disables row selection.
```

2024-06-15 19:59 UTC, Rapster requested changes
update description with js doc

2024-06-19 12:53 UTC, melloware commented
I fixed the PR with the JS doc descriptions

2024-06-19 12:53 UTC, merged