#12085 Core: Ajax performance (cleanseDomElement): No need to cleanse options elements
primefaces/primefaces pull request #12092
Opened 2024-06-08 20:49 UTC by cocorossello

In my test, with the performance measurement script provided in https://github.com/primefaces/primefaces/issues/12085

Without the patch:

```
AJAX updateElement : 104.026123046875 ms
common.js:751 Removed 269 DOM elements
common.js:750 AJAX updateElement : 1.4541015625 ms
common.js:751 Removed 1 DOM elements
common.js:750 AJAX updateElement : 1908.331787109375 ms
common.js:751 Removed 33193 DOM elements
```
With the patch:

```
AJAX updateElement : 99.87109375 ms
common.js:41 Removed 22 DOM elements
common.js:40 AJAX updateElement : 2.444091796875 ms
common.js:41 Removed 1 DOM elements
common.js:40 AJAX updateElement : 390.40087890625 ms
common.js:41 Removed 2413 DOM elements
```
Numbers are still way worse than the ones @melloware posted in https://github.com/primefaces/primefaces/issues/12085#issuecomment-2155018334, but this is an improvement

2024-06-08 22:29 UTC, cocorossello commented
I can see that still with the patch the performance is related to options size. If I don't render the options is much faster (scripting time)

I think it is because the event bubbles up (maybe?). In any case, if you need the remove event it can be fired with:

```
    // Remove the element from the DOM and trigger onRemove events for widget.destroy.
    // IMPORTANT: This must occur before jq.off() to ensure the on("remove") events remain registered.
    if (removeElement) {
        jq.triggerHandler("remove");
        jq.get(0).remove()
    }
```

This way performance numbers are good:

```
AJAX updateElement : 100.050048828125 ms
common.js:41 Removed 22 DOM elements
common.js:40 AJAX updateElement : 1.617919921875 ms
common.js:41 Removed 1 DOM elements
common.js:40 AJAX updateElement : 44.89892578125 ms
common.js:41 Removed 2808 DOM elements
```
Can you test if this is enough for primefaces to cleanup?

2024-06-09 11:25 UTC, melloware commented
@cocorossello yes let me test this in my real world scenarios

2024-06-09 11:42 UTC, melloware commented
OK i did the same behavior in the app with current code and your patch.

```
BEFORE CHANGE:
VM43:121 AJAX updateElement: 75.097900390625 ms
VM43:122 Removed 138 DOM elements
VM43:121 AJAX updateElement: 211.8740234375 ms
VM43:122 Removed 199 DOM elements
VM43:121 AJAX updateElement: 302.350830078125 ms
VM43:122 Removed 11642 DOM elements
VM43:121 AJAX updateElement: 259.909912109375 ms
VM43:122 Removed 12050 DOM elements
VM43:553 TabView: 4.22998046875 ms
VM43:554 Removed 247 DOM elements
VM43:121 AJAX updateElement: 234.94091796875 ms
VM43:122 Removed 12020 DOM elements
VM43:553 TabView: 3.346923828125 ms
VM43:554 Removed 424 DOM elements
VM43:121 AJAX updateElement: 223.243896484375 ms
VM43:122 Removed 11596 DOM elements
VM43:553 TabView: 53.662109375 ms
VM43:554 Removed 11468 DOM elements
VM43:121 AJAX updateElement: 26.52294921875 ms
VM43:122 Removed 128 DOM elements


AFTER CHANGE:
VM43:122 AJAX updateElement: 73.114013671875 ms
VM43:123 Removed 138 DOM elements
VM43:122 AJAX updateElement: 212.7138671875 ms
VM43:123 Removed 199 DOM elements
VM43:122 AJAX updateElement: 281.281005859375 ms
VM43:123 Removed 11642 DOM elements
VM43:122 AJAX updateElement: 257.079833984375 ms
VM43:123 Removed 12050 DOM elements
VM43:554 TabView: 4.556884765625 ms
VM43:555 Removed 247 DOM elements
VM43:122 AJAX updateElement: 248.955078125 ms
VM43:123 Removed 12020 DOM elements
VM43:554 TabView: 6.14501953125 ms
VM43:555 Removed 424 DOM elements
VM43:122 AJAX updateElement: 211.81298828125 ms
VM43:123 Removed 11596 DOM elements
VM43:554 TabView: 54.3701171875 ms
VM43:555 Removed 11468 DOM elements
VM43:122 AJAX updateElement: 20.333984375 ms
VM43:123 Removed 128 DOM elements
```

in my testing it seems your change performs about the same but i can confirm all the memory is still being cleaned up.

2024-06-09 13:43 UTC, cocorossello commented
Ok, I updated the PR with this findings. It still makes sense to skip the removal of select's children. (44ms skipping vs 130 without skipping)

2024-06-09 14:00 UTC, melloware requested changes

2024-06-09 14:00 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
> +            if (jq.prop("tagName") !== 'SELECT') { //No need to cleanse <option>s tag
```suggestion
            if (!jq.is("select")) { //No need to cleanse <option>s tag
```

2024-06-10 09:20 UTC, tandraschko commented
looks good to me
are the other childs to skip?

2024-06-10 11:35 UTC, melloware commented
I would think head would only be there if update="@all" but i have never used "@all" so i am not sure if head is in there.

2024-06-10 11:35 UTC, melloware approved these changes

2024-06-10 12:43 UTC, melloware requested changes

2024-06-10 12:43 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
> +            if (!jq.is("select")) { //No need to cleanse <option> tags
```suggestion
            if (!jq.is("select, svg, svg *")) { //No need to cleanse SVG or <option> tags
```
```suggestion
            if (!jq.is("select")) { //No need to cleanse <option> tags
```

2024-06-10 13:11 UTC, tandraschko commented
+1 to merge when you added svg exclude

2024-06-10 16:50 UTC, melloware approved these changes

2024-06-10 19:35 UTC, merged