Update to OpenPDF 2.0.2
primefaces/primefaces pull request #12171
Opened 2024-06-23 18:12 UTC by andreasrosdal

https://github.com/LibrePDF/OpenPDF/releases/tag/2.0.2

2024-06-23 18:33 UTC, melloware commented
Looks like the build is failing.

2024-06-23 18:35 UTC, melloware requested changes
We can support this as 2.x is JDK 17 only

> Java 17 or later is required for OpenPDF 2.0.0. This will allow using modern Java 17+ compatible syntax and libraries. Futhermore, it will ease maintenance effort because we don't support older Java versions.

2024-06-23 20:52 UTC, tandraschko commented
We decided to stay on java11, at least until migrate to Jakarta for 100%

2024-06-23 20:52 UTC, closed without merging

2026-09-30 22:41 UTC, SkylerMime commented
Could we update OpenPDF to a newer version for PF 17, since it is Java 17+?