Fix #12254/#11773: Datatable move lazy check to last
primefaces/primefaces pull request #12255
Opened 2024-07-04 17:30 UTC by melloware

Fix #12254: Datatable move lazy check to last
Fix #11773: Datatable move lazy check to last

2024-07-04 17:52 UTC, Rapster commented
Don't think it fixes the issue... If you enable filtering, and have active filters, you'll end up with the same issue no?

2024-07-04 18:07 UTC, melloware commented
Yes but this was how it was before the change in 14. Basically lazy is the most expensive check now and I tested both tickets and they are back to working like they were in 13

So it might not totally fix it but it fixes these two issues specifically and restores pre-14 behavior.

2024-07-04 18:11 UTC, melloware commented
Actually @Rapster both issues arose from row expansion and now it's evaluating the "value" of the datatable inside the expansion when it didn't before. So there is no way filtering would be active in this scenario.

2024-07-05 11:33 UTC, tandraschko commented
can we add a integration test for it, not breaking it again in future?

2024-07-05 12:46 UTC, melloware commented
Integration test added.  I have verified if this fix gets reverted this test fails because it blows up.

```java
throw new FacesException("GitHub #12254 was reverted as this should not throw an error on AJAX update!");
```

2024-07-05 22:31 UTC, Rapster commented
Ok, so from what I understand during RESTORE_VIEW phase, SKIP_ITERATION is set (by both impl I imagine) therefore the var bean will never be set and as a consequence you'll get a NPE. The best we can do is this PR, but eventually the problem will occur if the nested table enable filtering... In this case, no other choice than setting the lazy attr with a true/false

2024-07-05 22:33 UTC, Rapster approved these changes

2024-07-06 11:21 UTC, melloware commented
@Rapster you have assessed it accurately.  It could be combined with my other closed PR where we catch the exception and log them a better WARNING as to what to do?

2024-07-06 14:25 UTC, Rapster commented
I take back what I said, RowExpansion might be the issue... I was wondering how come we end up parsing the EL so late since it should have been in the viewstate, but since the rowexpansion is not expanded therefore not encoded, then the nested lazy EL is not parsed (not in viewstate then). If you set `DataTable#expandedRow` (which is a strange to be TBH) it works, because it's been encoded...

Anyway, even though we have a better understanding of whats going on... I don't have a better fix than this one yet... We can have specific log for this scenario (so people don't raise an issue everytime they face that problem)

2024-07-06 14:32 UTC, melloware commented
OK I added the explicit error checking back to `isLazy()` and suggested what the developer can do to mitigate the issue.

```java
 LOGGER.warning("Unable to automatically determine the `lazy` attribute, fallback to false. "
         + "Either define the `lazy` attribute on the component or make sure the `value` attribute doesn't resolve to `null`. "
          + "clientId: " + this.getClientId());
```

2024-07-06 14:47 UTC, Rapster commented
The issue that I have with this log, is that, in dev mode (as it should be quite verbose) people might not see it and will take no actions. I'm cool with the first one (and yet, don't know in which scenario it's not able to determine the type but it's quite surprising...) but second one should be in error and whatever the project stage

2024-07-07 11:42 UTC, melloware commented
OK updated to an ERROR an always regardless of ProjectStage.

2024-07-07 11:55 UTC, Rapster commented on primefaces/src/main/java/org/primefaces/component/api/UIData.java
> +                                + "clientId: " + this.getClientId());
remove useless this

2024-07-07 11:55 UTC, Rapster commented on primefaces/src/main/java/org/primefaces/component/api/UIData.java
> +                            + "Error: " + e.getMessage() + ". clientId: " + this.getClientId());
remove useless this

2024-07-07 11:55 UTC, Rapster requested changes
last coment and all good

2024-07-07 12:02 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/api/UIData.java
> +                            + "Error: " + e.getMessage() + ". clientId: " + this.getClientId());
Done!

2024-07-07 12:36 UTC, merged