Fix #12273: frozen columns right
primefaces/primefaces pull request #12277
Opened 2024-07-10 08:24 UTC by tvazquez-dev

Fix #12273

2024-07-10 11:40 UTC, melloware requested changes

2024-07-10 11:40 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java
> +        alignFrozenColumnsRight,
rename this property to `frozenColumnsAlignment` and the values will be "right" or "left" with the default "left"

Then in the widget you can make a boolean like `var isFrozenColumnsRight = this.cfg.frozenColumnsAlignment === "right";`

2024-07-10 11:41 UTC, melloware requested changes

2024-07-10 11:41 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java
> +        alignFrozenColumnsRight,
Don't forget to update `/docs/15.0/whatsnew.md` and `/docs/15.0/components/datatable.md`

2024-07-10 15:28 UTC, melloware requested changes

2024-07-10 15:28 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
> +            if (table.getFrozenColumnsAlignment().equals("right")) {
```suggestion
            if ("right".equalsIgnoreCase(table.getFrozenColumnsAlignment())) {
```

2024-07-11 11:14 UTC, melloware approved these changes

2024-07-13 23:12 UTC, Rapster commented
Can't we do these tests in one IT instead of 2? They look really similar

2024-07-18 12:16 UTC, tandraschko commented
+1 - please just check @Rapster comment

2024-07-19 16:43 UTC, melloware requested changes

2024-07-19 16:43 UTC, melloware commented on primefaces-integration-tests/src/main/webapp/datatable/dataTable046.xhtml
> +        <h:form id="form">
As @Rapster mentioned combined these two tests into one test with a SelectBooleanButton you can just toggle in the test.

2024-07-22 12:56 UTC, melloware approved these changes

2024-07-22 13:16 UTC, merged

2024-07-22 13:24 UTC, tandraschko commented
13.x?

2024-07-22 13:25 UTC, melloware commented
yep didn't realize this was against 13.X  should have noticed it. Going to merge to 15.0 main and revert this change.