Fix #12825: Make Dashboard scope configurable
primefaces/primefaces pull request #12826
Opened 2024-11-04 10:07 UTC by gako

see #12825

2024-11-04 12:25 UTC, melloware requested changes
Don't forget a note in 15.0.0 whatsnew.md and to add the new prop in dashboard.md in 15.0.0 folder?

2024-11-04 12:25 UTC, melloware commented on primefaces/src/main/java/org/primefaces/component/dashboard/DashboardBase.java
> +        scope
You can move scope up to be in alpha order.  I am trying to do this lately 😄

2024-11-05 10:55 UTC, gako commented on primefaces/src/main/java/org/primefaces/component/dashboard/DashboardBase.java
> +        scope
having a half-sorted list felt strange, so i've taken the liberty of sorting the whole list. :-)

2024-11-05 12:39 UTC, melloware approved these changes

2024-11-05 12:40 UTC, merged