Fix #12853: Datatable filter toggler via js
primefaces/primefaces pull request #12881
Opened 2024-11-13 18:57 UTC by gako

see #12853

2024-11-13 20:20 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
> +     * @param {function | null} callback will be executed after animation is finished. (see jquery fadeToggle method)
```suggestion
     * @param {() => void | null} callback will be executed after animation is finished. (see jquery fadeToggle method)
```

2024-11-13 20:23 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
> +     * @param {() => void | null} callback will be executed after animation is finished. (see jquery fadeToggle method)
```suggestion
     * @param {() => void) | null} callback will be executed after animation is finished. (see jquery fadeToggle method)
```

2024-11-13 20:30 UTC, melloware requested changes

2024-11-13 20:30 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
> +        var _self = this;
We typically us `$this` instead of `_self`

2024-11-14 08:37 UTC, tandraschko commented
there should be a JS API section in the datatable.md

2024-11-14 12:51 UTC, melloware approved these changes

2024-12-03 10:45 UTC, tandraschko commented
TBH i would just remove bindFilterToggleEvents and only provide 1 binding method
providing 2 similar APIs is just not required

2024-12-03 12:08 UTC, tandraschko commented
and IMO the manual call is the better one as binding requires some init code, which will break when the DT is updated and so on. toggleFilter is more safe and intuitive

2024-12-03 20:52 UTC, melloware requested changes

2024-12-03 20:52 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
> +}
Doesn't this style need to be applied somewhere?

2024-12-12 10:11 UTC, gako commented on primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
> +}
yes, if you want the column filter to be hidden initially on page load you have to set the stylev 'ui-filter-togglable' in the datatable itself.

2024-12-13 13:10 UTC, melloware approved these changes

2024-12-13 13:11 UTC, merged

2024-12-13 13:11 UTC, melloware commented
Thanks @gako this is great!

2024-12-14 15:49 UTC, melloware commented
@gako you can see it in action here: https://quarkus-faces-melloware-8a6a34c1.koyeb.app/ui/data/datatable/filter.xhtml

nice work.