Proposal #4332 - Modernize Documentation
primefaces/primefaces pull request #4334
Opened 2018-12-17 21:03 UTC by Rapster

2018-12-18 07:05 UTC, cnsgithub requested changes
Looks good for a first draft. How did you convert it?

The tables are messed up.

![image](https://user-images.githubusercontent.com/13161711/50137497-9e44b480-029b-11e9-957f-a7d6dddae066.png)

2018-12-18 07:08 UTC, cnsgithub requested changes
Missing code formatting/indentation:

![image](https://user-images.githubusercontent.com/13161711/50137635-072c2c80-029c-11e9-8e3e-7d7e9ff2fda3.png)

2018-12-18 07:15 UTC, mertsincan commented
Maybe, http://pdf2md.morethan.io/ :D I used it :D Looks good @Rapster ;)

2018-12-18 07:22 UTC, cnsgithub reviewed
How can we derive these component and attribute information automatically from sources?

![image](https://user-images.githubusercontent.com/13161711/50137694-43f82380-029c-11e9-8df0-3287df3079d1.png)

Suggestion:
1. Use [Freemarker](https://github.com/apache/freemarker) templates, iterate over components/tags/attributes/renderers/etc. defined in `primefaces-p.taglib.xml`, `faces-config.xml `or somewhere else and dynamically create snippets.
```freemarker
<#list components as component>
   ...
   ${component.name} ${component.description}
   <#list component.attributes as attribute>
      ...
   </#list>
</#list>
```
2. Include those snippets in `index.adoc` during doc generation.
````adoc
include::{snippets}/comp1.adoc[]
````
3. Use `asciidoctor-maven-plugin` to generate HTML.
4. Publish generated HTML to GitHub Pages.

2018-12-18 10:39 UTC, Rapster commented
Thanks @cnsgithub I simply did a quick conversion pdf to markdown, and clean up the table of content so far. I'll figure out something about the generation of component properties, thanks for sharing you thoughts. Once done, I'll start cleaning up the whole adoc (indentation, table, etc.)

2018-12-18 16:13 UTC, christophs78 commented
Realy happy to hear someone tries to modernize the Documentation!

2018-12-19 12:04 UTC, melloware commented
@Rapster also it looks like everything is in 1 giant ADOC file?  Should we have an ADOC file per component to make future updates and commits easier?  I know this your first cut so I apologize if that was in your plans.

2018-12-19 13:08 UTC, Rapster commented
Yup, that's the plan. Don't worry, I'm glad you're thinking the same :wink:

2018-12-22 19:37 UTC, cnsgithub commented on src/main/asciidoc/ftl/component.ftl
> +# ${tag.description}
@Rapster I like your approach very much! 👍  Please consider escaping for asciidoc within ftl templates.

2018-12-22 19:53 UTC, Rapster commented on src/main/asciidoc/ftl/component.ftl
> +# ${tag.description}
I'll have a look, thanks for saying it :wink:

2018-12-24 11:36 UTC, tandraschko commented
Thanks for your great work so far!

I just wonder if we could move code from the new dependency:
`                     <dependency>
                         <groupId>org.primefaces</groupId>
                         <artifactId>primefaces-asciidoc</artifactId>
                         <version>1.0-SNAPSHOT</version>
                     </dependency>`
inside PF itself? 
I don't like to introduce new dependencies, it was always annoying with the maven plugin....

2018-12-24 13:15 UTC, Rapster commented
That was my first intent, I tried and didn't work and from doc it says clearly:

> Note that processors must be included in the plugin’s execution classpath, not in the project’s.

But I kinda like it this way, as it gives is a clear distinction between PF core and PF asciidoc API. And don't worry, it's not a proper new dependency, just used during plugin execution.

2019-03-06 12:49 UTC, Rapster commented
@cagataycivici I recently add a look on your last commit. I'm not sure what has ben decided... But I think this PR might answer to #4332, you'll find a sample here https://github.com/primefaces/primefaces/issues/4332#issuecomment-451780963

2019-03-06 12:53 UTC, tandraschko commented
yep please check our discussion and share your thoughts @cagataycivici :D
i think the community including mert really agreed on a cool way with very much autogeneration.

2019-03-12 16:28 UTC, Rapster commented
I just feel the whole conversation we had about what's the best for documentation is completely being ignored. It's the shame really, I took a lot of my free time for this as I was quite convinced (and I still am) it was the right way to solve the documentation problem...

From what I can see right now:
- one folder per version: I don't think it's good idea as you'll congest the repo
- nothing generated: a lot of incoherences can happen. We (and the community) will have to handle the documentation tickets in case of adding/updating/deleting attributes.
- docsify

2019-03-12 16:48 UTC, melloware commented
I am with @Rapster this is the way to go for documentation.  Its what all the Spring Boot projects are doing.

2019-03-14 14:28 UTC, Rapster commented
I just feel the whole conversation we had about what's the best for documentation is completely being ignored. It's a shame really, I took a lot of my free time for this (after finding a common ground) as I was quite convinced (and I still am) it was the right way to solve the documentation problem...

From what I can see right now:
- one folder per version: I don't think it's good idea as you'll congest the repo with time, specially that git does that for you
- nothing generated: a lot of incoherences can happen. We (and the community) will have to handle the documentation tickets in case of adding/updating/deleting attributes. I thought we all agreed that it's a pretty cool feature.
- docsify: sounds nice but very limited, handles only static content. AsciiDoctor handles custom directive. The final result on AsciiDoctor looks better IMO
- markdown: Since the core is asciidoctor, using asciidoc makes sense (and it has more features than markdown). But in your case, docsify id markdown based.
- migration: you've been rewriting what I've already done so far... Kind of a waste of time on both sides.

That's all I can say right now considering the present modifications (and from what I can understand)

But again, as said Thomas, sharing your thoughts would be a great help for the community to understand what led to that decision.

2019-04-16 15:29 UTC, tandraschko commented
As i already stated, i can't change it and don't like the decision of PrimeTek and that you even don't get an statement.
However, i can't change it and will close the PR.

Thanks for your hard work.

2019-04-16 15:29 UTC, closed without merging