DataExporter: Enhance DataExporter to support other components #4414
primefaces/primefaces pull request #4416
Opened 2019-01-11 16:30 UTC by ravihariharan

Creating a PR for discussion for support for DataExporter for use with other components

`Exporter<TABLE extends UIComponent>`
i could only extends it to UIComponent  since UIData would have excluded all UITree components. 

Open to review and suggestion to make this PR better.

2019-01-11 16:32 UTC, tandraschko commented
lets discuss this after the release. RC1 is coming soon.

2019-01-11 16:43 UTC, ravihariharan commented
@tandraschko  i was trying to sneak it to 6.3 since it was quick refactor for rename a class and extract a interface. 

I guess we can wait if RC1 is round the corner.

2019-03-19 16:06 UTC, ravihariharan commented
@tandraschko let me know you thought of how this could be extended.

2019-04-07 11:41 UTC, tandraschko commented
will do it when i have more time, probably in ~2-3 weeks

2019-06-08 12:17 UTC, melloware commented
@ravihariharan Would this PR fix this issue by allowing export of TreeTable?  https://github.com/primefaces/primefaces/issues/10

If so this would be a big win.

2019-06-12 14:49 UTC, ravihariharan commented
@melloware  the refactor will allow any developer to provide a custom export implementation. We should be able to use to use it for TreeTable .  

DataTable will have default export support for PDF, CVS, XML. At a later date we can also build the default export support for TreeTable.

2019-06-25 14:38 UTC, Rapster commented
I like this PR, though see my comments please

2019-06-25 16:31 UTC, ravihariharan commented
@Rapster  i could not find any comments in the commit.

https://github.com/primefaces/primefaces/pull/4416/commits/7c6828f50c5d4115c006a791d365075fdabf5b79

2019-06-25 16:32 UTC, Rapster commented
Don't look in the commit but PR itself

2019-06-25 16:43 UTC, ravihariharan commented
@Rapster  the only comments  i see 
'I like this PR, though see my comments please'
`Don't look in the commit but PR itself`

checked both the issue and PR :(
https://github.com/primefaces/primefaces/issues/4414
https://github.com/primefaces/primefaces/pull/4416

2019-06-25 16:52 UTC, Rapster requested changes

2019-06-25 16:52 UTC, Rapster commented on src/main/java/org/primefaces/component/export/Exporter.java
> +public interface Exporter<TABLE extends UIComponent> {
Rename into `T`, as you mentionned it does not necessarily need to be a `DataTable` or a `TABLE` at all

2019-06-25 16:52 UTC, Rapster commented on src/main/java/org/primefaces/model/charts/ChartDataSet.java
> +/**
Why chartjs files have been modified in this PR? Wrong pull?

2019-06-25 16:57 UTC, ravihariharan commented on src/main/java/org/primefaces/model/charts/ChartDataSet.java
> +/**
i had merged @melloware  code to test and incorrectly merged it to my PR .
@melloware code is already merged to master.

2019-06-25 16:59 UTC, ravihariharan commented on src/main/java/org/primefaces/component/export/Exporter.java
> +public interface Exporter<TABLE extends UIComponent> {
i messed up my github repository. can this be fixed with a new PR after this one is merged ?  or i will redo with a new repository and a new PR.

2019-06-25 17:08 UTC, Rapster commented on src/main/java/org/primefaces/component/export/Exporter.java
> +public interface Exporter<TABLE extends UIComponent> {
There are plenty ways to about it, but you don't need to create a new repo.  A new branch should do (but I think you can even solve your problem without doing that). Play with it :wink:

2019-06-28 01:22 UTC, ravihariharan commented on src/main/java/org/primefaces/component/export/Exporter.java
> +public interface Exporter<TABLE extends UIComponent> {
@Rapster i was able to get the orphaned  PR using   
```
git fetch https://github.com/primefaces/primefaces.git refs/pull/4416/head:4416PR
git checkout 4416PR

```
These changes are now
![image](https://user-images.githubusercontent.com/15189434/60310531-588b3780-9921-11e9-983e-76e379ab6a2b.png)

The above will create a PR with a new ID so not sure if there is a better way?

2019-06-28 08:19 UTC, Rapster commented on src/main/java/org/primefaces/component/export/Exporter.java
> +public interface Exporter<TABLE extends UIComponent> {
It's okay, just close the old PR

2019-06-28 11:36 UTC, awenger63 commented
Hi, do you know if this could be use whith pe:sheet ?

2019-06-28 13:20 UTC, closed without merging

2019-06-28 13:22 UTC, ravihariharan commented
New PR : DataExporter: Enhance DataExporter to support other components #4414 #4949

Review comments fixed.

2019-06-28 13:30 UTC, ravihariharan commented
> pe:sheet



> Hi, do you know if this could be use whith pe:sheet ?

The objective of this PR is to provide only a interface for developer to implement a custom export for any component. 

```
https://primefaces.github.io/primefaces/7_0/#/components/dataexporter
customExporter
```