Fix primefaces#4263: OverlayPanel - Ensure top/left is not out of view
primefaces/primefaces pull request #4558
Opened 2019-02-19 08:59 UTC by fanste

This fix uses the ``offset`` of the ``offsetParent`` of the to be positioned overlay as maximum allowed negative values for top and left. The ``offsetParent`` will respect e,g, ``position:fixed`` parents.

It is based on the current 7.0.RC3

2019-02-19 09:02 UTC, fanste commented
@tdtappe please run a test with this fix

2019-02-20 07:29 UTC, fanste commented
BTW: I did not find the option ``offset`` for jQuery UI's version of ``position``. Is this still supported / needed?`I did not see any difference when I removed it for testing.

2019-02-20 09:12 UTC, tdtappe commented
> @tdtappe please run a test with this fix

Works for me :-) Thanks a lot!!!

2019-02-20 16:40 UTC, melloware approved these changes

2019-03-19 16:00 UTC, tandraschko commented
Can you fix the conflicts?

2019-03-20 07:22 UTC, fanste commented
Should be good for now.
( A lot to learn about how to work with github :D )

2019-04-24 15:19 UTC, tandraschko commented
@fanste Could you check this case here? https://github.com/tdtappe/primefaces-test/tree/overlay-panel-position
The "bottom test" is always in background now
not sure if releated to your fix but would be great if we can fix both issues for the testcase.

2019-05-27 07:20 UTC, fanste commented
I had some time to take a look at this issue again. I don't think that we can fix that 'automatically'.

The button with the overlay is inside a div element (i call it parent). The modal's div element (i call it modal) is on the same level as the parent. Chancing the z-index on the overlay and modal has no effect as long as the parent does not have a higher z-index as the modal.

But automatically applying a z-index to each parent may destroy the look of the website. Therefore I suggest to either let it as it is and the user has to apply the z-index manually to each parent element that needs it or we introduce a new attribute for `p:overlayPanel` like `applyZindexToParent=true|false` with `false` as default. Additionally with an other new attribute `zindexParentSelector` (with * as default) the user could even decide which elements require an automatically applied z-index.

2019-07-17 12:45 UTC, tandraschko commented
@fanste can you rebase it?

2019-07-18 13:49 UTC, fanste commented
Looks like it should be correct again.

2019-08-21 12:55 UTC, tandraschko commented
Can someone test some cases?

2019-10-14 09:11 UTC, tandraschko commented
i tried to retest it by myself but something is wrong.
the second overlaypanel is covered by a modal.
can you check this?
it might be a different bug.

2019-10-16 06:51 UTC, fanste commented
What do you mean with "second overlaypanel"? The one that is opend with the button "bottom-test"? Then please have a look at your comment from the 24th april 2019 and my answer form the 27th may 2019. I already described the problem and two possibile solutions.

An alternative solution may be to move the model parallel to the overlay (inside the `position:fixed`-div). With the correct z-index for the button, overlay and modal it will be correct again. But that won't work when any parent has `position:relative`.

2019-10-16 07:27 UTC, tandraschko commented
oh, i see
need to check it in detail

2019-11-27 19:55 UTC, melloware requested changes

2019-11-27 19:55 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
> +        _self = this;
we typically use $this instead of _self.

2019-11-28 12:03 UTC, melloware approved these changes

2020-06-03 18:05 UTC, melloware commented
@tandraschko do you think this is safe to merge.  We are past 8.0 release and so far my testing for this has been good.

2020-06-15 19:50 UTC, merged