Add support for InputNumber and additional constraints. Fixes #5165
primefaces/primefaces pull request #5172
Opened 2019-09-18 14:08 UTC by NicolaIsotta

2019-09-18 14:23 UTC, melloware requested changes

2019-09-18 14:23 UTC, melloware commented on src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java
> +                }
I would add `LOGGER.log(Level.WARN, "Failed setting Spinner max value: " + ex.getMessage());` I don't like empty try catches.

2019-09-18 14:23 UTC, melloware commented on src/main/java/org/primefaces/metadata/transformer/impl/BeanValidationInputMetadataTransformer.java
> +                }
I would add `LOGGER.log(Level.WARN, "Failed setting Spinner min value: " + ex.getMessage());` I don't like empty try catches.

2019-09-18 14:24 UTC, tandraschko reviewed
Is DecimalMin in BVal 1.0?

2019-09-18 14:31 UTC, melloware commented
> Is DecimalMin in BVal 1.0?

Yes DecimalMin and Max are in 1.0.

2019-09-22 20:08 UTC, tandraschko commented
+1
But please also change the Date to LocalDate in this class

2019-09-23 07:48 UTC, NicolaIsotta commented
> +1
> But please also change the Date to LocalDate in this class

Sure. Two questions:
- Since time could be in the calendar pattern, maybe LocalDateTime is better?
- Should I consider BV 2.0 new time constraints (`@PastOrPresent` and `@FutureOrPresent`)? We can use class names like in OutputLabelRenderer so no need to change dependency.

2019-09-23 08:21 UTC, tandraschko commented
1) Not sure. CC @christophs78
2) yes. We can not upgrade as PF would not work on JavaEE6/7 then

2019-09-23 14:38 UTC, christophs78 commented
Calendar and DatePicker currently (7.1-dev; Master-Branch) supports LocalDate as minDate and maxDate-values. (And java.util.Date for backward-compatibility-reasons.)
See [https://primefaces.github.io/primefaces/7_1/#/components/datepicker?id=datepicker](https://primefaces.github.io/primefaces/7_1/#/components/datepicker?id=datepicker)
Maybe we should add support for LocalDateTime for minDate and maxDate-Attributes for convenience-reasons. And for edge-cases where Calendar and DatePicker are used with showTime=true. And maybe we should support LocalTime for timeOnly=true.

2019-09-24 16:22 UTC, NicolaIsotta commented
Updated with LocalDate e BV 2.0 new time contraints.

2019-09-24 19:51 UTC, tandraschko commented
+1 
Can someone retest it?
I assume it also works with DatePicker?

2019-09-24 20:06 UTC, melloware commented
It should work with DatePicker, @NicolaIsotta can you confirm and then I will take a pass at testing it.

2019-09-25 11:04 UTC, NicolaIsotta commented
I haven't tested yet with Calendar. DatePicker and LocalDateTime/java.util.Date combination seems a bit broken ATM.

2019-09-25 12:18 UTC, tandraschko commented
Whats happening?
@christops78 can you assist pls?

2019-09-25 13:19 UTC, christophs78 commented
@NicolaIsotta: Applied a fix/work-around for 4625 (for LocalDateTime) during my work on java.time-support. Please look into [https://github.com/primefaces/showcase-facelift/blob/master/src/main/webapp/ui/input/datePickerJava8.xhtml](https://github.com/primefaces/showcase-facelift/blob/master/src/main/webapp/ui/input/datePickerJava8.xhtml). Compare this with [https://github.com/primefaces/showcase-facelift/blob/master/src/main/webapp/ui/input/datePicker.xhtml](https://github.com/primefaces/showcase-facelift/blob/master/src/main/webapp/ui/input/datePicker.xhtml)
Could you look please look into this and give me feedback? (I know this solution is not ideal, but it´s a work-around without needing to to a deepdive into the clientside JS.) 

@tandraschko, @mertsincan: Is it possible to deploy the 7.1-dev-Showcase? Think it would be ideal to have the 7.0-Release Showcase deployed and in parallel the 7.1-dev-Showcase?

@NicolaIsotta: I know there is some room for improvement (as already mentioned) for Type-Support for minDate/maxDate-Attributes. I will work on this sometime in october.

2019-09-25 13:35 UTC, NicolaIsotta commented
I'll open a new issue for datepicker to avoid cluttering this conversation.

`I know there is some room for improvement (as already mentioned) for Type-Support for minDate/maxDate-Attributes. I will work on this sometime in october.`
mindate and maxdate already support LocalDateTime, no need for additional work.

2019-09-25 14:06 UTC, tandraschko commented
+1 
Can you merge plz melloware?

2019-09-25 14:09 UTC, merged