Improve pattern handling for Datepicker
primefaces/primefaces pull request #5191
Opened 2019-09-26 13:15 UTC by NicolaIsotta

Fixes #5186

2019-09-26 13:16 UTC, melloware commented
@christophs78 please review!

2019-09-26 19:18 UTC, christophs78 requested changes
I am on holidays with my family. So only limited time and code-review on my iPad. :-)
First of all thanks for your work. And thanks for fixing a few things i missed when moving Calendar and DatePicker to java.time!
Overall your work looks really excellent!
Could you add a few mutations of getValueAsString_LocalDateTime to CalendarUtilsTest?

2019-09-26 19:18 UTC, christophs78 commented on src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
> +    public String calculatePattern() {
Please add some test-methods for this method. Think we should cover usecases like usedefinied dateFormat with time (-> removeTime) and the calculated TimeOnlyPatterns for 12 and 24 hour-format.

2019-09-26 19:18 UTC, christophs78 commented on src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
> +    public String calculatePattern() {
Please add a few tests for this method. Eg userdefinied pattern where we need to remove time. TimeOnlyPattern with 12 and 24 hours.

2019-09-26 19:21 UTC, christophs78 commented
Please add the issue-number to the name/label of this PR.

2019-09-26 19:44 UTC, melloware commented
Title updated.

2019-09-27 10:09 UTC, NicolaIsotta commented
I'll add some test as soon as I can.
While testing I discovered the original java 8 PR ( #4782 ) broke `p:calendar` when `timeOnly="true"`.
I'll try to fix that too.

2019-09-29 07:33 UTC, christophs78 commented
Seems like i broke UICalendar#calculateTimeOnlyPattern with the java 8 PR.

Generated client-side JS with 7.0:
`pf.cw("Calendar","widget_form_time",{id:"form:time",popup:true,locale:"en",dateFormat:"m\/d\/y HH:mm",timeOnly:true,`

Generated client-side JS with 7.1-dev:
`pf.cw("Calendar","widget_form_time",{id:"form:time",popup:true,locale:"en",dateFormat:"HH:mm",timeOnly:true`

2019-09-29 07:38 UTC, christophs78 commented
Maybe we should use your new method calculateWidgetPattern also for CalendarRenderer. (Maybe with some modifications.)

2019-09-30 07:56 UTC, NicolaIsotta commented
I've already fixed it, but I've not commited yet as it's still broken with LocalTime (p:calendar always expects a date part). I'll have to make some special workaround

2019-10-02 14:54 UTC, christophs78 commented on src/main/java/org/primefaces/util/CalendarUtils.java
> +                }
I don´t think, it´s necessary to add the new forCalendarInput parameter.
We should be able to to something like `if (calendar instanceof Calendar) {`

2019-10-02 15:13 UTC, NicolaIsotta commented on src/main/java/org/primefaces/util/CalendarUtils.java
> +                }
Yeah you're right, it simpler with instanceof

2019-10-02 17:39 UTC, christophs78 approved these changes
Tested your PR on my machine against the showcase. Everything looks fine.
We should add a few test´s to ensure this a bit complex "construct" does not break in the future. But we do not necessarily need to to this in this PR. I (or we) can add additional test´s with a future PR.

2019-10-03 07:27 UTC, NicolaIsotta commented
I'll commit some tests later today

2019-10-04 16:16 UTC, christophs78 commented
@melloware - From my perspective this PR is finished and ready to be merged.

2019-10-04 16:52 UTC, melloware commented
@tandraschko any objection?  I have looked it over and it looks good and they added a bunch of unit tests to it as well.

2019-10-04 16:53 UTC, melloware approved these changes

2019-10-07 11:29 UTC, merged