#3549 DataTable: (inline-)edit - row-mode: set focus to...
primefaces/primefaces pull request #5233
Opened 2019-10-09 10:27 UTC by christophs78

… the first input-field in the row

2019-10-09 11:27 UTC, melloware requested changes

2019-10-09 11:27 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
> +            let inputs=$(row).find('input, select, textarea, button');
I think a better selector would be `:input:enabled` which finds the first input,select,textarea radio button or any input element that is actually NOT disabled.

2019-10-09 11:27 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
> +                firstInput.focus();
I think you should just make this one line with `inputs.first().focus();` no need to declare variable for this yet.

2019-10-09 12:00 UTC, tandraschko commented
let is supported in IE?

2019-10-09 12:08 UTC, melloware commented
It looks like Let is supported in IE11 https://stackoverflow.com/a/2356926/502366

2019-10-09 12:26 UTC, christophs78 commented
> 
> 
> It looks like Let is supported in IE11 https://stackoverflow.com/a/2356926/502366

Yep. :-) https://caniuse.com/#feat=let

2019-10-09 12:32 UTC, christophs78 commented
@melloware : Thanks for your feedback. Done.

2019-10-09 12:52 UTC, mertsincan commented
Hi @christophs78,

Thanks a lot for the PR! But, I think you need to made these changes in showRowEditors. Because, row editor has lazy feature. 
```
      if(this.cfg.rowEditMode === "lazy") {
            this.lazyRowEditInit(row);
        }
```
When users use this feature, your code won't work for them.

Also, could you please use 'var' instead of 'let'? We don't use ES6 syntax in PrimeFaces.

Maybe, 
```
showRowEditors: function(row) {
        var isFirstItemFocused = false;
        row.addClass('ui-state-highlight ui-row-editing').children('td.ui-editable-column').each(function() {
            var column = $(this);
    /** Maybe **/
            if (!isFirstItemFocused) {
               var inputs = column.find('...');
               if (inputs.length > 0) {
                    ...
                    isFirstItemFocused = true;
                }
            }
    /**********/
            column.find('.ui-cell-editor-output').hide();
            column.find('.ui-cell-editor-input').show();
        });
    },
```

Best Regards,

2019-10-09 13:24 UTC, christophs78 commented
@mertsincan: Thanks for your valuable feedback.

2019-10-09 13:39 UTC, melloware approved these changes

2019-10-09 13:40 UTC, melloware commented
Good teamwork on this PR. :)

2019-10-11 08:23 UTC, tandraschko commented
is the feedback from mert about lazy already implemented?

2019-10-11 10:57 UTC, christophs78 commented
Yes, it is. (https://github.com/primefaces/primefaces/pull/5233/commits/b03082954ede0e4552554e34a6bf3a16f63633cc)

2019-10-11 10:59 UTC, merged