Fixes #5320 - Timeline: timeZone and browserTimeZone are ignored when manually set
primefaces/primefaces pull request #5328
Opened 2019-11-13 18:38 UTC by jasonex7

Fixes #5320

2019-11-13 18:50 UTC, melloware requested changes

2019-11-13 18:50 UTC, melloware commented on src/main/java/org/primefaces/component/timeline/TimelineBase.java
>      }
You can remove getDir() entirely as RTLAware interface is a default interface that does exactly this right?

2019-11-13 18:51 UTC, melloware approved these changes

2019-11-13 19:01 UTC, christophs78 commented
I think we should bring back browserTimeZone (or clientTimeZone when we look at Schedule) for this. IMO the timeZone used server-side should be decoupled from the clientTimeZone. (eg we want to set server-side timeZone but do not want to set a fixed clientTimeZone)

2019-11-13 19:19 UTC, melloware commented
we should standardize the name like clientTimeZone for both Schedule and Timeline

2019-11-13 19:56 UTC, jasonex7 commented
So `clientTimeZone` will affect vis Timeline component and `timeZone` will affect TimelineEvent start and end dates, is that correct?

2019-11-14 12:07 UTC, christophs78 commented
Thanks, looks good. 
(server-side) timezone is the "anchor". 
We send `start: new Date('2019-11-14T14:00:00+01:00'), end: new Date('2019-11-14T22:00:00+01:00')` from the server to the client.
OOTB the client (=browsers) transfers this into his (client)TimeZone. As an exmple: you want to know when the formular 1 race start. In this case you expect the browser to transfers this into your timezone. So you know when to turn on the tv.
When you attend an conference in madrid and look on the website of this converence you expect to see the starting-time in the (client)TimeZone of Madrid. For this usecase you would set clientTimeZone.

2019-11-14 12:08 UTC, christophs78 commented
@melloware : IMO this PR is ready to be merged.

2019-11-14 12:12 UTC, tandraschko commented
all right
please also change the migration guide

2019-11-14 12:12 UTC, merged