#5717: DatePicker: smart behaviour for showTime and timeOnly-attributes with value-binding to LocalDate/LocalDateTime/LocalTime
primefaces/primefaces pull request #5718
Opened 2020-03-22 11:18 UTC by christophs78

Still need to do some QA (and maybe refactoring), but already looks good.

2020-03-23 11:59 UTC, melloware requested changes

2020-03-23 11:59 UTC, melloware commented on src/main/java/org/primefaces/component/api/UICalendar.java
> +        Boolean timeOnly = (Boolean) getStateHelper().eval(PropertyKeys.timeOnly);
Instead of "Smart" maybe isTimeOnlyDetected() is a better name?

2020-03-23 11:59 UTC, melloware commented on src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
> +        Boolean showTime = (Boolean) getStateHelper().eval(PropertyKeys.showTime);
Detected again instead of Smart?

2020-03-24 13:49 UTC, tandraschko commented
1. Im not sure about the "Detect" suffix
2. Shouldn't we pass the Value type to the "detect" methods? (we already extract the value type, which also check the list generic type e.g.)

2020-03-24 15:49 UTC, christophs78 commented
>     2\. Shouldn't we pass the Value type to the "detect" methods? (we already extract the value type, which also check the list generic type e.g.)

For some calls we already know the value type, for other not:
![grafik](https://user-images.githubusercontent.com/10461942/77446922-56420500-6def-11ea-8c1d-1c7cb11e02ef.png)

2020-03-24 19:02 UTC, christophs78 commented
I´ll try a second approach where we call `DatePickerBase#setShowTime` from `DatePickerRenderer#encodeScript`. (Only when showTime ist not explicit set.) Hope this works and makes it easier. With the current approach i dislike passing FaceContext arround.

2020-03-25 15:36 UTC, closed without merging