PR-5831 add chooseButtonTitle,uploadButtonTitle,cancelButtonTitle in FileUpload
primefaces/primefaces pull request #5954
Opened 2020-05-25 17:40 UTC by doleron

This PR is intended to fix the issue https://github.com/primefaces/primefaces/issues/5831 by including new attributes to `FileUpload` component: _chooseButtonTitle_, _uploadButtonTitle_ and _cancelButtonTitle_. Note that these new attributes refer to the `title` html attribute for the respective buttons inside the component.
Tested on Chrome:
![image](https://user-images.githubusercontent.com/9665358/82833743-50bb7680-9e95-11ea-8f20-2912a597aee7.png)
Firefox:
![image](https://user-images.githubusercontent.com/9665358/82833756-616bec80-9e95-11ea-916e-d559f67a3040.png)
Edge:
![image](https://user-images.githubusercontent.com/9665358/82833791-7c3e6100-9e95-11ea-99e3-bfc93e8987d2.png)
Internet Explorer:
![image](https://user-images.githubusercontent.com/9665358/82833822-9415e500-9e95-11ea-9c7b-272dbf8e99e8.png)

2020-05-25 17:41 UTC, melloware approved these changes

2020-05-25 17:44 UTC, melloware commented
Can you look at #1261 to see if you can also fix it with this PR?

2020-05-25 18:12 UTC, doleron commented
Yes, I just replied there.

2020-05-25 19:52 UTC, melloware approved these changes

2020-05-25 19:52 UTC, doleron commented
I just sent a commit including 'title' attribute for simple mode which works just such as native `title` in `<input type='file' title='...'>` attribute:

```xhtml
<p:fileUpload id="uploader3" mode="simple" skinSimple="true" title="my custom title"/>
```
![image](https://user-images.githubusercontent.com/9665358/82840100-ccbeba00-9ea7-11ea-8623-cad94cf17ea1.png)

2020-05-26 11:20 UTC, melloware requested changes

2020-05-26 11:20 UTC, melloware commented on docs/9_0/components/fileupload.md
>  | onAdd | null | String | Callback to execute before adding a file.
I think you need to add `title` here to the docs.

2020-05-26 11:31 UTC, melloware approved these changes

2020-05-26 11:41 UTC, merged