Primefaces ai
primefaces/primefaces pull request #5969
Opened 2020-05-31 13:03 UTC by doleron

Hi, this PR is intended to propose 3 new components for PrimeFaces:

- **SmartCam**: component to apply computer vision detection algorithms to the camera stream in client-side. By default, SmarCam performs face detection like a regular smartphone camera does. Optionally face landmarks can be retrieved as well and other custom object detection algorithms can be applied.
- **SpeechRecognition** uses built-in browser Web Speech API to provide multi-language speech recognition.
- **Speaker**: Spearker is a voice synthetizer based on Web Speech API

Examples of usage can be found here: https://github.com/doleron/primefaces-showcase/tree/primefaces-ai 

## SmartCam - face detection + landamark detection

![image](https://user-images.githubusercontent.com/9665358/83352491-213bbc80-a322-11ea-8b1a-71342da502d4.png)

## SamrtCam - object detection

![image](https://user-images.githubusercontent.com/9665358/83352516-5e07b380-a322-11ea-9cd3-861e216c2a82.png)

## Speech Recognition

![ezgif-6-9af93bc014e4](https://user-images.githubusercontent.com/9665358/83352728-0ec28280-a324-11ea-8be6-75822fe84d4b.gif)

## Speaker

![image](https://user-images.githubusercontent.com/9665358/83352824-bf308680-a324-11ea-867e-4e82fd6b8c74.png)

It is noteworthy that they are in 'proposal stage' yet. Thus, in the current code there is no documentation and some must-to-have functionalities are not provided but tracked out in the backlog.

2020-05-31 19:00 UTC, christophs78 commented
Very interesting!

Which browsers do support this?
https://caniuse.com/#search=SpeechRecognition does not work yet with Firefox. What´s the state for the other two features?

2020-05-31 19:42 UTC, doleron commented
Firefox does support speech recognition, at least the new versions:

![image](https://user-images.githubusercontent.com/9665358/83361189-3a159380-a35d-11ea-8827-417708e13a20.png)

In my  browser I needed to enable `media.webspeech.recognition.enable` and `media.webspeech.recognition.force_enable`.

2020-05-31 20:04 UTC, melloware commented
Can Smartcam just replace the current Photocam components. The js library is quite old and no longer being updated.  Plus you can’t pick which camera front or back without hacking the js.  So if smartcam is robust to replace pbotocam we should just make it the new Photocam component instead of a new component. Thoughts?

2020-05-31 20:47 UTC, doleron commented
In my point of view I agreed, updating PhotoCam to HTML5 is really a good thing to do.

2020-05-31 21:37 UTC, melloware commented
a few general comments I will do a deeper code review later but.

1. Instead of 'language' property use 'locale' which is standard for most components and look how TimeLine does it...
```java
wb.attr("locale", timeline.calculateLocale(context).toString());
```
Calculate Locale checks faces-config.xml for locale, your current browser settings or lets you set it specifically.  This is how language is handled in most components.  And no need to set default to "en-US" as `LocaleUtils` will pick an appropriate default for you.

2. I don't think anyone will approve of the `.ai` subpackage or new `ai` taglib.

3. Camera selection "rear or front" should be a first class citizen.  See this forum post: https://forum.primefaces.org/viewtopic.php?f=3&t=46682

4. We should make sure we support these 2 open tickets so we can close them:
https://github.com/primefaces/primefaces/issues/2223
https://github.com/primefaces/primefaces/issues/2152

2020-05-31 23:40 UTC, doleron commented
Ok,

I will submit another PR covering:
1. Upgrading of PhotoCam to HTML5 keeping the current set of features
2. Fixes of https://github.com/primefaces/primefaces/issues/2223 and  https://github.com/primefaces/primefaces/issues/2152
3. Support to device list/selection

2020-06-01 08:30 UTC, tandraschko commented
- in general +1 if it works fine in all browsers
- i would not create a second "ai" taglib
- formattings are not correct in some JS files
- all the points from melloware

2020-06-01 10:45 UTC, christophs78 commented
Is all browsers except IE11 Ok? (I would expect IE11 is (almost) history when PrimeFace 9.0 get´s released.)

2020-06-01 11:35 UTC, melloware requested changes

2020-06-01 11:35 UTC, melloware commented on src/main/java/org/primefaces/component/ai/smartcam/SmartCamRenderer.java
> +
I think all `callbacks` should use `on` like onmodel, onpredict, and onimageHandler to follow PF conventions.

Why not make them `'p:ajax` events as well?

2020-06-01 11:35 UTC, melloware commented on src/main/java/org/primefaces/component/ai/speechrecognition/SpeechRecognitionRenderer.java
> +                .callback("speechErrorHandler", "function(error)", component.getSpeechErrorHandler());
These callbacks should be `onspeech` and `onerror`

2020-06-01 11:54 UTC, melloware requested changes

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/smartcam/smartcam.js
> +        if (!("autoStart" in this.cfg)) {
You don't need to initialize this autostart variable at all just say later in the code `if (this.cfg.autoStart)` and its false by default and will only ever be true if you passed in true.  Javascript will assume false even if the variable is undefined.

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/smartcam/smartcam.js
> +		return await facemesh.load();
`await` makes this not work in IE.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/smartcam/smartcam.js
> +
Would rather see this short circuited with `if (!div) return;` rather than all that indented code inside the `if (div)`

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/smartcam/smartcam.js
> +        	$this = this;
move the `$this = this` up to the `var` section at the beginning of the method where you declare `var div`

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/smartcam/smartcam.js
> +	        if(navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
If these are not true should these be also checked up above where the `if div` check is so we can short circuit this whole method.

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/speaker/speaker.js
> +            console.error('SpeechSynthesisUtterance.onerror');
Shouldn't this be a `callback` hook so users can get the onerror?  Maybe even and AJAX event `callBehavior`

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/speaker/speaker.js
> +            console.log('SpeechSynthesisUtterance.onend');
Shouldn't this be a `callback` hook so users can get the onerror?  Maybe even and AJAX event `callBehavior`

2020-06-01 11:54 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/ai/speechrecognition/speechrecognition.js
> +	langs:
See my previous comment about changing to `locale` and none of this will be necessary.

2020-06-10 23:38 UTC, closed without merging