Jdk9 support
primefaces/primefaces pull request #5996
Opened 2020-06-05 16:49 UTC by GedMarc

Allows for modular referencing from prime faces

2020-06-05 16:53 UTC, melloware requested changes

2020-06-05 16:53 UTC, melloware commented on pom.xml
> +                                <moduleInfoFile>${basedir}/src/moditect/module-info.java</moduleInfoFile>
/src/conf/ is probably a better folder

2020-06-05 16:53 UTC, melloware commented on src/moditect/module-info.java
> +
/src/conf/ is a better folder

2020-06-05 16:54 UTC, melloware commented
Did you generate this file by hand?  How did you know how to format it?

2020-06-05 17:24 UTC, GedMarc commented
Interestingly... already have this in production at a client (didn't want to make it until it was ready)

Yes this is produced by hand, going through many... many **many** iterations.
Operational co-ordinates here : https://mvnrepository.com/artifact/com.guicedee.services/primefaces

Source code for these co-ordinates here (Special consideration to the shading taking place, i'm pulling in itext and the others)
https://github.com/GedMarc/JWebMPDevKit/tree/master/GuicedEE/Services/gee4j/primefaces

2020-06-05 17:25 UTC, GedMarc commented
Oh, um, i did the jackson json, org.json, hibernate, and apache commons libraries ones as well, if you need any clarity ask :)

2020-06-05 20:38 UTC, tandraschko commented
does this fully work on older application servers with java8?

2020-06-06 13:24 UTC, melloware commented
I built this PR with JDK8 and ran the showcase with JDK8 and everything is working fine.  This just seems to put a module-info.class in the root of the JAR and doesn't make any changes other than that.

@GedMarc just double checking that is the correct location of module-info.class for it to be detected in the JAR?  Also it was put in the primefaces.jar but NOT in the primfaces-jakarta JAR so you might need to modify the SHADE plugin slightly to grab this?

2020-06-06 13:38 UTC, melloware requested changes
See comments

2020-06-07 03:06 UTC, GedMarc commented on pom.xml
> +                <version>3.2.4</version>
3.2.4 introduces new methods that conflict with the shade/moditect combination

2020-06-07 03:30 UTC, GedMarc commented on pom.xml
> +                <version>3.2.4</version>
```
Receiver class io.yupiik.maven.shade.transformer.RelocationTransformer does not define or inherit an implementation of the resolved method 'abstract void processResource(jav
a.lang.String, java.io.InputStream, java.util.List, long)' of interface org.apache.maven.plugins.shade.resource.ResourceTransformer.
```

2020-06-07 03:30 UTC, GedMarc commented
this PR requires a few other decisions to be made, as well as unstable in the moditect plugin when referencing multiple shaded jars

future request.

2020-06-07 03:30 UTC, closed without merging