Please use the last co-ordinates for the javax. namespace for version 9
primefaces/primefaces pull request #5998
Opened 2020-06-05 17:15 UTC by GedMarc

2020-06-05 20:37 UTC, tandraschko commented
why do we need jaxb?

2020-06-05 20:37 UTC, tandraschko commented
also we should never add a impl dependency to PF

2020-06-06 13:27 UTC, melloware requested changes

2020-06-06 13:27 UTC, melloware commented on pom.xml
> +            <optional>true</optional>
Why do we need this runtime?  PF should not need this

2020-06-06 13:27 UTC, melloware commented on pom.xml
> +            <optional>true</optional>
Why do we need this impl PF should not need this...only the API.

2020-06-06 13:27 UTC, melloware commented on pom.xml
> +            <version>3.0.3</version>
Impl not needed...

2020-06-07 03:47 UTC, GedMarc commented
Hmm apparently for the tests
Let's see how scoping them into tests will work

2020-06-07 11:51 UTC, melloware commented
Well it looks like ValueExpressionAnaylyzer test is failing with an initialization failure.

2020-06-08 12:22 UTC, melloware commented
@GedMarc @tandraschko I think the reason he added the JAXB-impl was for the unit tests because in Java 11+ they no longer include JAXB.  Same problem we had with the Showcase we had to update if you want to run JDK11.  It works fine without the impl in Java 8.  But we should probably add it at "TEST" scope so the PF build works in JDK8 or 11.  

Also I wonder if we should have our Travis build be Oracle JDK8 and OpenJDK 11 as the two JDK's we build for?

2020-06-08 12:25 UTC, tandraschko commented
its ok for me as test dependency, otherwise -1

+1 to add a java11 travis build

2020-06-08 12:37 UTC, melloware commented
OK I will work on adding JDK11 to Travis.

2020-06-08 14:03 UTC, melloware commented
PR https://github.com/primefaces/primefaces/pull/6013 supersedes this PR so closing.

2020-06-08 14:03 UTC, closed without merging