Imagecropper
primefaces/primefaces pull request #6078
Opened 2020-06-25 00:37 UTC by GedMarc

#6077 

Use JDK 8 native Path for referencing, important for JDK 11 and up particularly with modules enabled

2020-06-25 11:23 UTC, melloware commented
@GedMarc looks like you have 3 checkstyle violations.
```
[ERROR] /home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java:228: 'else' child has incorrect indentation level 28, expected level should be 24. [Indentation]
[ERROR] /home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java:228:1: File contains tab characters (this is the first instance). [FileTabCharacter]
[ERROR] /home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java:229: 'else' child has incorrect indentation level 28, expected level should be 24. [Indentation]
```

2020-06-25 11:24 UTC, melloware requested changes

2020-06-25 11:24 UTC, melloware commented on src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java
> +	                    inputStream = Files.newInputStream(locationPath, StandardOpenOption.READ);
CheckStyle

2020-06-25 12:32 UTC, GedMarc commented
Hmm so I'm trying to isolate here, this looks to be a 2 parts here so I'm going to need a bit of guidance - 

This fix is working for me right now, i'll try clean it all up and see what repercussions  i have caused myself

The Paths should take care of everything linux/mac/ and updated. The NIO library has huge updates relating to file management, e.g. using FileStream here may be replaceable with FileChannel (MacOS gets usually a 60% file read increase, i'll find the link somewhere), 

For me in particular, JLink native imaging uses the JRT filesystem... which is readonly, so i have another problem where the uploaded files are trying to be stored in the classpath on a read only module native image xD i can route to a static location easy enough but can't seem to specify where to save the files

* How do I add a custom location to be specified for the uploaded files, in the showcase when i push the button it goes to /demo/images/....

:D :D

2020-06-25 12:36 UTC, melloware commented
I think it has to be relative to the web application root, and that is why we had to add the OWASP Path Traversal check: 
https://github.com/primefaces/primefaces/issues/3268

So there is no way to specify some other file location i think it has to be under the web app.  But I did not design this component  it has been like this for years.

2020-06-26 05:18 UTC, GedMarc commented
Oh dear.... 

We do either a static location on a server more designed for static content and reverse proxy a location into there
or save the data in a table to be served by a servlet at another location. 
Saving or updating the actual web application with file data, hmmm...

Can you lead me to the widget that is implemented? Is this something that we are open to? Retrieving the data in the same manner as file upload into a stream rather than saving it down to the file system?

For the showcase can always display the crop image in a base 64 data image saving on some disk space for the showcase server?

2020-06-26 11:33 UTC, melloware commented
So if you have 9.0-SNAPSHOT running locally and grab 9.0-SNAPSHOT Showcase from master you can see recently these 2 ticket were implemented: 
https://github.com/primefaces/primefaces/issues/12
https://github.com/primefaces/primefaces/issues/4837

And 2 new Showcase examples were added for ImageCropper.

![image](https://user-images.githubusercontent.com/4399574/85852764-408e0400-b77f-11ea-8822-40f255118fea.png)

2020-06-30 11:23 UTC, closed without merging