Fix #5978: FileDownload: add Ajax support
primefaces/primefaces pull request #6267
Opened 2020-08-30 14:58 UTC by jepsar

Fix #5978

Please note that documentation (and showcase) is still to do. I'd like to wait on feedback first and then add the documentation.

2020-08-30 15:04 UTC, melloware reviewed
This looks impressive

2020-08-30 17:36 UTC, tandraschko commented
Please dont change from Iäindex loop to for loop, thats by design for performance

2020-08-30 18:16 UTC, jepsar commented
> Please dont change from index loop to for loop, thats by design for performance

👍 Reverted.

2020-08-31 18:23 UTC, christophs78 commented
(very) minor point: please add a entry to thirdpartylibs.md

2020-09-01 13:07 UTC, tandraschko commented
What are the exact changes in DynmicSourceContentBuilder?

2020-09-01 13:08 UTC, tandraschko commented
if its just the "component != null"; please dont refactor the whole class. T

2020-09-01 13:18 UTC, tandraschko commented
also added the first performance hint (the indexloop stuff) here: https://github.com/primefaces/primefaces/wiki/Contributing-to-PrimeFaces

2020-09-01 16:53 UTC, jepsar commented
> What are the exact changes in DynmicSourceContentBuilder?
> if its just the "component != null"; please dont refactor the whole class.

I noticed that what we needed to download a file is very similar to the GraphicImage component: https://primefaces.github.io/primefaces/8_0/#/components/graphicimage?id=how-it-works

So I checked the renderer and found that I could almost use the `DynamicContentSrcBuilder` to create a URI to load in the JavaScript. The only thing we don't have in the `FileDownloadActionListener` was a component.

The component in the `DynamicContentSrcBuilder` is used to get the `ValueExpression` (we already have that) and to add parameters (we don't really need that). So I decided to add a constructor taking a `ValueExpression` and a component which can be null. That was the least drastic change I could think of.

I doubted to move the parameters part to a separate method to reduce indentation.

2020-09-01 17:47 UTC, tandraschko commented
i see
then please double check your code - you decode a null "src" in worst case because you "return" in the if statements

2020-09-01 18:12 UTC, jepsar commented on src/main/java/org/primefaces/util/DynamicContentSrcBuilder.java
> +        return encodeResourceURL(context, src, cache);
@tandraschko are you referring to this line? If so, src could be null originally:

https://github.com/primefaces/primefaces/blob/d05387b93bd5fc68d825bc5d325cc49472110cf5/src/main/java/org/primefaces/util/DynamicContentSrcBuilder.java#L127

Shall I change that into throwing a FacesException?

2020-09-01 18:17 UTC, tandraschko commented
i would remove src var and return null at the end of the method

2020-09-01 18:23 UTC, jepsar commented
> (very) minor point: please add a entry to thirdpartylibs.md

@christophs78 any idea what the first column should contain? Most (of not all) links are broken. I'll add the library without a link in the first column.

2020-09-01 18:37 UTC, melloware commented
@jepsar those links get generated by our JSDocs process so for your new code there will be nothing there yet.  So leave it "link less" like I do for FontAwesome

2020-09-01 19:28 UTC, melloware requested changes

2020-09-01 19:28 UTC, melloware commented on docs/9_0/core/thirdpartylibs.md
> +| download.js | 4.2 | http://danml.com/download.html |
I usually put these in alphabatical order to make them easier to find.

2020-09-02 08:35 UTC, merged

2020-09-02 08:40 UTC, tandraschko commented
did some small refactorings
thanks for the good PR!

a showcase example would be great!

2020-09-02 09:09 UTC, jepsar commented
> did some small refactorings
> thanks for the good PR!
> 
> a showcase example would be great!

Sure, I was going to. I'll add documentation as well. 😃