Fix #4446: Only process loaded (clientside) row expansions
primefaces/primefaces pull request #6326
Opened 2020-09-17 13:13 UTC by fanste

2020-09-17 14:02 UTC, melloware commented
As mentioned in the ticket we should test with sorting, filtering, and paging to make sure its still working properly.

2020-09-17 15:37 UTC, melloware requested changes

2020-09-17 15:37 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
> +    },
Looks like your formatting spacing here in JavaScript is a little off compared to rest of the file?

2020-09-21 11:45 UTC, melloware approved these changes

2020-09-25 09:45 UTC, tandraschko commented
the code looks ok

2020-09-25 13:17 UTC, melloware commented
@tandraschko Its been tested by @fanste @rider87 and myself.  Think this is safe to merge??

2020-09-30 09:08 UTC, merged