Fix #5905: AutoComplete: emptyMessage click listener
primefaces/primefaces pull request #6353
Opened 2020-09-26 15:10 UTC by jepsar

Fix https://github.com/primefaces/primefaces/issues/5905

2020-09-27 14:13 UTC, melloware approved these changes

2020-09-27 15:45 UTC, melloware requested changes

2020-09-27 15:45 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +        this.panel.on('click', function() {
make it `click.emptyMessage` I like to add namespaces so when debugging we can easily tell where the onClick came from

2020-09-27 17:32 UTC, tandraschko commented
IMO "emptyMessage" as eventname is quite unclear when its triggered

2020-09-27 17:37 UTC, jepsar commented
> IMO "emptyMessage" as eventname is quite unclear when its triggered

Agreed. I tried to keep it in line with `moreText`. I think both should be suffixed with "Click".

2020-09-28 08:23 UTC, jepsar commented
@tandraschko @melloware Shall I rename the events to `emptyMessageSelect` and `moreTextSelect` (and update the breaking changes in the migration guide)?

2020-09-28 11:09 UTC, tandraschko commented
i think so
WDYT @melloware ?

2020-09-28 11:23 UTC, melloware commented
Yes I think we should its more specific name to what is happening.  I like "Select"

2020-09-28 17:17 UTC, jepsar commented
Done (including migration guide).

2020-09-28 17:33 UTC, melloware approved these changes

2020-09-30 09:10 UTC, merged