#6511: AutoComplete: optionally allow to consume REST-endpoint for suggestions
primefaces/primefaces pull request #6512
Opened 2020-11-15 11:19 UTC by christophs78

work in progress

2020-11-15 12:01 UTC, christophs78 commented
![image](https://user-images.githubusercontent.com/10461942/99184382-aab14080-2742-11eb-8ded-a9a01fdb54a7.png)

2020-11-15 12:07 UTC, tandraschko commented
yep, thats expected
in think it can be a great addition to components to provide REST integration points in future

2020-11-15 19:29 UTC, tandraschko commented
We should think about maiking it a clientbehavior or at least call it "completeEndpoint"

2020-11-15 19:51 UTC, tandraschko commented
And we should think about adding the Rest Models to PF

2020-11-15 19:54 UTC, christophs78 commented
> And we should think about adding the Rest Models to PF

which package-name?

2020-11-16 12:00 UTC, tandraschko commented
looks good to me
Could we maybe think about other cases/components and collect some possible endspoints?

if we have maybe, we should maybe think about something like:

<p:endpoint event="complete" value="/myurl" />

instead of

<p:ajax event="complete" ... />

2020-11-16 12:40 UTC, melloware requested changes

2020-11-16 12:40 UTC, melloware commented on src/main/java/org/primefaces/model/rest/AutoCompleteSuggestion.java
> +    private String label;
Should be serializable and add equals(), hashcode(), and toString() methods.

2020-11-16 12:45 UTC, melloware commented
How about instead of "completeEndpoint" we call it "restCallback" or something more generic. I can also see this being useful on any component that supports `lazy/dynamic` and `f:selectItems`.  And for the custom model object it could be `RestSelectItem` or possibly even just use `SelectItem` as the callback POJOs??  Just some ideas.

2020-11-16 12:48 UTC, tandraschko commented
i dont think "restCallback" is good. each feature might need an own endpoint.

2020-11-16 13:05 UTC, melloware commented
OK how about just generically "endpoint" then?

2020-11-16 13:07 UTC, tandraschko commented
no :D
each feature needs a unique name like "feature1Endpoint" or "feature2Endpoint"
therefore a clientbehavior could be a good way

2020-11-16 13:38 UTC, christophs78 commented
One thing we need to have an eye on is the amount of rendering-logic we duplicate. (Have it in our classic server-based Java-code and have a second JavaScript-based implementation.)
When we think - as an extreme example - about DataTable it IMO makes limited sense to duplicate this. 
It´s IMO kind of trade-off between what we gain on a per-component/feature-base from adding REST-support and which complexity do we add with this. And how well do REST-endpoints play togehter with this component/feature and it´s JSF-serverside logic.
Do we have some conrete ideas based on our brainstorming where REST-integration would make sense? (on a per componenten/feature-base)
Personally i would invest maybe a few hours per month on this topic. (Including integration tests.) But i personally won´t start a hundreds of hours side-project: ;-)

2020-11-16 14:23 UTC, tandraschko commented
i personally think we only should use it for smaller features like this one here.
maybe lazy-load of selectItems of different other components like selectOneMenu would be a good improvement, too. Or search in selectOneMenu.
probably anything related to a "input autocomplete"

i cant think of other usecases now. As you already said, DataTable would be to much effort to make it work for all cases.

2020-11-16 15:56 UTC, tandraschko commented
I think we should leave it as it for now (no behavior etc), lets see if we implement other cases in the future.

I think a small but good improvement would be to have a real "root-model" for each possible rest endpoint. WDYT?
Somelike like:
```
class AutoCompleteSuggestionResponse {
     private List<AutoCompleteSuggestion> suggestions;
}
```

+ melloware suggestions

2020-11-16 18:13 UTC, christophs78 commented
> ```
> class AutoCompleteSuggestionResponse {
>      private List<AutoCompleteSuggestion> suggestions;
> }
> ```

I´ll look into this. I have to check how Jackson handles this OOTB.

> and add mellowares suggestions (hashcode, equals, serializable, tostring)

Do you have some prefered implementation for hashcode and equals? (Maybe an existing class which does it in your prefered way i may look into.) Personally i think serializeable is not direct fit to kind of DTO which is returned as JSON by a REST-service. But it should not to any harm. To some degree same for hashcode and equals.

2020-11-16 18:19 UTC, christophs78 commented
> And for the custom model object it could be `RestSelectItem` or possibly even just use `SelectItem` as the callback POJOs?? Just some ideas.

SelectItems has some features, AutoComplete does not support. AutoComplete is just value + label. No disabled, no description, no explicit escape, no noSelectionOption.

2020-11-16 18:23 UTC, christophs78 commented
Overall its a REST-API. So `AutoCompleteSuggestion` and maybe `AutoCompleteSuggestionResponse` are just convenience-classes. Theoretically AutoComplete may consume a PHP, NodeJS, C# or whatever REST-service.

2020-11-16 18:32 UTC, melloware commented
OK Agreed all around.

2020-11-16 18:35 UTC, christophs78 commented
`List<AutoCompleteSuggestion>` results in following example JSON:
```javascript
[{"value":"3","label":"Luna-Blue"},{"value":"4","label":"Luna-Amber"},{"value":"5","label":"Luna-Green"},{"value":"6","label":"Luna-Pink"}]
```

With something like `AutoCompleteSuggestionResponse` we results in:
```javascript
{"suggestions":[{"value":"3","label":"Luna-Blue"},{"value":"4","label":"Luna-Amber"},{"value":"5","label":"Luna-Green"},{"value":"6","label":"Luna-Pink"}]}
```

IMO this does not make sense. We may compensate this by adding Jackson-Annotations to `AutoCompleteSuggestionResponse` but i don´t think we want to add Jackson (compile-time) dependency. And maybe there some people who don´t use Jackson but something else.

2020-11-17 09:10 UTC, tandraschko commented
nope, we shouldnt add jackson.
i just thought its easier to have a single response-root model for each possible endpoint in the future.
I dont care if we have a "suggestions" subnode in json or not TBH :)

2020-11-18 16:59 UTC, christophs78 commented
I have the following class on my dev-machine:
```java
public class AutoCompleteSuggestionResponse {

    private List<AutoCompleteSuggestion> suggestions = new ArrayList<>();

    public AutoCompleteSuggestionResponse(List<AutoCompleteSuggestion> suggestions) {
        this.suggestions = suggestions;
    }

    public void addSuggestion(AutoCompleteSuggestion suggestion) {
        suggestions.add(suggestion);
    }

    public List<AutoCompleteSuggestion> getSuggestions() {
        return suggestions;
    }

    public void setSuggestions(List<AutoCompleteSuggestion> suggestions) {
        this.suggestions = suggestions;
    }
}
```

But i personally like it that much.

Look into the showcase-PR - IMO following is very straight forward:
```java
@GET
@Path("/autocomplete")
@Produces({ MediaType.APPLICATION_JSON })
public List<AutoCompleteSuggestion> autocomplete(@QueryParam("query") String query) {
	String queryLowerCase = query.toLowerCase();
	List<Theme> allThemes = service.getThemes();
	return allThemes.stream()
			.filter(t -> t.getName().toLowerCase().contains(queryLowerCase))
			.map(t -> new AutoCompleteSuggestion(Integer.toString(t.getId()), t.getDisplayName()))
			.collect(Collectors.toList());
}
```

IMO it makes good use of streams. Yes we can put this into AutoCompleteSuggestionResponse. But i don´t thinks this improves the REST-service-code.

2020-11-18 17:01 UTC, melloware commented
I say lets leave it out for now then.

2020-11-19 10:51 UTC, tandraschko commented
in the docus i would do:
`completeEndpoint="#{request.contextPath}/rest/theme/autocomplete"`
instead of
`completeEndpoint="../../rest/theme/autocomplete"`

2020-11-19 10:51 UTC, tandraschko commented
after this change i would merge it

2020-11-19 16:03 UTC, christophs78 commented
We integrated this today in our real-world-project. And it turn´s out after all there are reasons to introduce `AutoCompleteSuggestionResponse`. The REST-endpoint may limit the amount of results it send´s to the client. So we need a flag to indicate there may be more results. This flag has to be located in `AutoCompleteSuggestionResponse`.

And i have to look that emptyMessage work´s with REST-endpoint to.
Update: emptyMessage work with completeEndpoint OOTB.

I'll get in touch after that's done.

2020-11-19 17:31 UTC, melloware commented on src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +                            var moreTextEncoded = $("<div>").text($this.cfg.moreText).html();;
Double ;; on this line

2020-11-19 17:37 UTC, christophs78 commented on src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +                            var moreTextEncoded = $("<div>").text($this.cfg.moreText).html();;
Thanks for pointing me on this!

2020-11-19 17:42 UTC, christophs78 commented
1. Docu is updated.
2. `AutoCompleteSuggestionResponse` is introduced and supports `moreText` via `moreAvailable`-property.

equals/hashcode thing IMO makes as i mentioned before limited sense for DTO´s we send to the client. If we realy want to add equals/hashcode for this please point me to some kind of blueprint-class.

2020-11-19 17:55 UTC, tandraschko commented
i would just auto-generate it for the suggestion class, also implement serializable for both models
so you auto-avoid duplicate items in a list e.g.

2020-11-19 18:55 UTC, christophs78 commented
> i would just auto-generate it for the suggestion class, also implement serializable for both models
> so you auto-avoid duplicate items in a list e.g.

done :-)

2020-11-20 08:48 UTC, tandraschko commented
looks good for me now
maybe we should add a hint in the docs "the json looks like this ... but we have a model class for it" 
or something similar?

2020-11-20 11:42 UTC, merged

2020-11-20 11:42 UTC, tandraschko commented
Thanks for the great PR!