#6812 ChartJS: Upgrade to V3
primefaces/primefaces pull request #7146
Opened 2021-03-20 19:00 UTC by christophs78

2021-03-20 19:04 UTC, christophs78 commented
At the current point this PR show´s most of our showcase-examples are up and working again.
But need some more time. And not sure whether we should keep our models almost unchanged and do - where necessary - some magic in the background to map it to ChartJS 3. Maybe we should do some breaking changes on our side to better reflect the API of ChartJS 3.

2021-03-20 20:10 UTC, melloware commented
I was afraid of that. Maybe we could mark some deprecated and do some magic behind the scenes as well?

2021-03-21 16:03 UTC, melloware commented
RC2 was just released: https://github.com/chartjs/Chart.js/releases/tag/v3.0.0-rc.2

2021-03-21 18:47 UTC, christophs78 commented
All of our showcase-examples are up and working again.
I should take some more time to think about our API do some code-cleanup.

2021-04-02 19:43 UTC, melloware commented
Charts 3.0.0 is final!

https://github.com/chartjs/Chart.js/releases/tag/v3.0.0

2021-04-02 20:42 UTC, melloware commented
Already a 3.0.1: https://github.com/chartjs/Chart.js/releases/tag/v3.0.1

2021-04-04 13:38 UTC, melloware commented
3.0.2 https://github.com/chartjs/Chart.js/releases/tag/v3.0.2

2021-04-11 11:44 UTC, melloware commented
3.1.0: https://github.com/chartjs/Chart.js/releases/tag/v3.1.0

2021-04-17 12:49 UTC, melloware commented
3.1.1 out: https://github.com/chartjs/Chart.js/releases/tag/v3.1.1

2021-04-18 15:14 UTC, christophs78 commented
Getting the extender-mechanism back 2 work seems to be complicated....
Got it kind of working with using window.setTimeout - trick, but far away from ideal. Some better ideas? (Probably needs at least another few hours to play around.)

```javascript
function chartExtender() {
	//copy the config options into a variable
	var options = $.extend(true, {}, this.cfg.config);

	console.log('passe ChartJS-settings an');

	options = {
		plugins: {
			"title": {"display": true, "text": "Bar Chart"}
		}
	};

	//merge all options into the main chart options
	var tmp = $.extend(true, this.cfg.config, options);
	console.log(tmp);

	// this.chart.update();
	var that = this;
	window.setTimeout(() => { updateChart(that.widgetVar); }, 10);
};

function updateChart(widgetVar) {
	let chart = PF(widgetVar).chart;
	chart.options.plugins.title.text = 'new title';
	chart.update();
}
```

2021-04-18 15:27 UTC, melloware commented
Hmmm maybe i am confusing something but the Extender just manipulates the CFG object before the Chart is created?  Its just supposed to be a way for people to add their own code and plugins before passing it to the chart before its created `this.chart = new Chart(this.ctx, this.cfg.config); `.

Or is something different in the new Charts?

2021-04-18 17:59 UTC, christophs78 commented
`_render` is called before `init`. And probably some internal difference in ChartJS 3 which makes it a bit more complicated to change configuration after ChartJS was initialized. I´ll try to move in some way the extender from to `init` to  `_render`.

2021-04-18 18:13 UTC, christophs78 commented
> Hmmm maybe i am confusing something but the Extender just manipulates the CFG object before the Chart is created? Its just supposed to be a way for people to add their own code and plugins before passing it to the chart before its created `this.chart = new Chart(this.ctx, this.cfg.config); `.
> 
> Or is something different in the new Charts?

It was my fault. I just was temporarily confused by ChartJS 3 - data structures and had to adapt the extender - example.

2021-04-18 18:36 UTC, christophs78 commented
From my point of view this PR is read for review.

One thing someone should do some time later is to cross-check our XyzChartDataSet - classes against current ChartJS-documentation. IMO there a some gaps introduced over years during upgrading ChartJS.

2021-04-19 11:39 UTC, melloware commented
Excellent work @christophs78

2021-04-19 11:42 UTC, melloware requested changes

2021-04-19 11:42 UTC, melloware commented on src/main/java/org/primefaces/component/charts/ChartRenderer.java
> +            // TODO: requires some refactorings for hasAttrs
Remove TODO?

2021-04-19 11:42 UTC, melloware commented on src/main/java/org/primefaces/component/charts/ChartRenderer.java
> +//                encodeScaleCommon(writer, cScales);
Delete commented line?

2021-04-19 11:42 UTC, melloware commented on src/main/java/org/primefaces/component/charts/ChartRenderer.java
> +//                encodeScaleCommon(writer, rScales);
Delete commented line?

2021-04-19 11:42 UTC, melloware commented on src/main/java/org/primefaces/component/charts/ChartRenderer.java
> +//    }
Delete

2021-04-19 19:40 UTC, melloware approved these changes

2021-04-25 14:19 UTC, melloware commented
3.2.0 https://github.com/chartjs/Chart.js/releases/tag/v3.2.0

2021-05-08 16:02 UTC, melloware commented
Looks like some conflicts to resolve now.

2021-05-13 20:02 UTC, tandraschko commented
+1 from my side if everything is working

2021-05-14 15:53 UTC, melloware commented
@christophs78 You think this is safe to merge or do you want to upgrade to latest ChartsJS first?

2021-05-14 19:44 UTC, merged