Implement #7569: SelectManyMenu: provide PF Selenium - wrapper and integrationtests
primefaces/primefaces pull request #7571
Opened 2021-07-10 19:59 UTC by christophs78

2021-07-11 11:16 UTC, melloware requested changes

2021-07-11 11:16 UTC, melloware commented on primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectManyMenu.java
> +    public void toogleSelection(WebDriver webDriver, String label, boolean withMetaKey) {
`toggle` not `toogle`

2021-07-11 18:06 UTC, christophs78 commented on primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectManyMenu.java
> +    public void toogleSelection(WebDriver webDriver, String label, boolean withMetaKey) {
thanks for pointing be on this typo!

2021-07-12 09:45 UTC, tandraschko commented
why do you pass WebDriver webDriver everywhere? just use getWebDriver from inheritance

2021-07-12 17:33 UTC, christophs78 commented
> why do you pass WebDriver webDriver everywhere? just use getWebDriver from inheritance

Thanks for pointing me on this!

2021-07-12 18:21 UTC, melloware approved these changes

2021-07-12 18:35 UTC, merged