#7712: OutputPanel: Added skeletons facet to output panel
primefaces/primefaces pull request #7728
Opened 2021-08-20 16:58 UTC by jepsar

PR 1/2

2021-08-20 17:15 UTC, melloware requested changes

2021-08-20 17:15 UTC, melloware commented on docs/11_0_0/components/outputpanel.md
> +    <f:facet name="skeletons">
facets usually are not plural so "skeleton" instead of "skeletons"?

2021-08-20 17:55 UTC, melloware approved these changes

2021-08-20 19:45 UTC, tandraschko commented on primefaces/src/main/java/org/primefaces/component/outputpanel/OutputPanelRenderer.java
> +    public void decode(final FacesContext context, final UIComponent component) {
remove "final"

2021-08-20 19:46 UTC, tandraschko commented on primefaces/src/main/java/org/primefaces/component/outputpanel/OutputPanelRenderer.java
> +    protected void renderLoading(FacesContext context) throws IOException {
dont remove the panel param, might be used for overloading and doesnt hurt

2021-08-20 20:26 UTC, melloware approved these changes

2021-08-21 09:12 UTC, merged

2021-08-22 14:45 UTC, Rapster commented
Unless the facet have to be a skeleton, (but I don't think so from what I saw already) I don't think "skeleton" is the right name for this. Maybe "loading"?

2021-08-22 14:50 UTC, jepsar commented
It does not need to contain skeleton components per se, it can contain anything. I do like the term skeleton for the facet though.

2021-08-22 14:51 UTC, tandraschko commented
in general "loading" as name would be a bit nicer, also for the new datascroller
is is the content, when the component is "loading" the new content

i can rename if you like

2021-08-22 14:52 UTC, Rapster commented
Yes please 😉

2021-08-22 14:53 UTC, jepsar commented
I'll rename it