Fix #7818: Rating: Keyboard Support
primefaces/primefaces pull request #7908
Opened 2021-10-01 18:26 UTC by jepsar

Fix #7818

@weiprd please review

I did not add this to the what's new file as I'm not sure if this will end up in 11 or 12.

@mertsincan the focussed state does not look great. So this might require additional styling. Also, inline block might be more suitable for this component.

2021-10-01 19:19 UTC, melloware requested changes

2021-10-01 19:19 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/rating/rating.js
> +        this.jq.attr('tabindex', this.tabindex);
Why not add this line to the bindEvents and unbindEvents code?

2021-10-02 07:19 UTC, jepsar commented
If this goes to 11, I need to add a note to 11's change log.

2021-10-02 11:35 UTC, melloware approved these changes

2021-10-02 11:35 UTC, melloware commented
This looks really good and is a great addition for accessibility.  @tandraschko I think this should go in 11.0.0 WDYT?

2021-10-02 16:47 UTC, melloware commented
Can you rebase your PR i updated owasp-suppressions.xml to fix the error that is blocking your build.

2021-10-02 16:55 UTC, tandraschko commented
im ok if mert does some styling for it
otherwise i feel its not complete

2021-10-04 08:06 UTC, jepsar commented
@melloware I rebased, but now I no longer can run the showcase:

> java.lang.ClassNotFoundException: javax.faces.webapp.FacesServlet

2021-10-04 08:11 UTC, tandraschko commented
profiles has been changed, check the readme

2021-10-04 08:14 UTC, jepsar commented
OK, got it running now

2021-11-02 07:06 UTC, merged

2021-11-02 07:06 UTC, mertsincan commented
@jepsar, Thanks a lot for your contribution!