add: CSP: Report only #8520
primefaces/primefaces pull request #8521
Opened 2022-03-07 13:17 UTC by cnsgithub

2022-03-07 13:40 UTC, melloware requested changes

2022-03-07 13:40 UTC, melloware commented on docs/12_0_0/core/contentsecuritypolicy.md
> +In large web applications you might decide to report CSP violations only as a start instead of directly forcing them. Browsers will report CSP violations to a user-defined HTTP endpoint then.
Dont forget to also add to /gettingstarted/configuration.md file

2022-03-07 13:40 UTC, melloware commented on primefaces/src/main/java/org/primefaces/csp/CspPhaseListener.java
> +            // TODO forward compatibility via report-to directive and Report-To header left out for the moment to reduce complexity
Remove TODO?

2022-03-07 13:40 UTC, melloware commented
@cnsgithub long time!   Thanks for the PR this looks pretty good to me just a couple of comments.

2022-03-07 13:50 UTC, cnsgithub commented
> just a couple of comments.

Done.

Thanks for the quick review, @melloware

2022-03-07 14:10 UTC, melloware approved these changes

2022-03-07 14:11 UTC, melloware commented
The only other thing you might want to add is /gettingstarted/whatsnew.md just to let people know the new options are available.

2022-03-07 16:12 UTC, tandraschko commented
IMO we should introduce `CSP_POLICY_REPORT_ONLY` as new param for allowing setting multiple params, not just report-uri

and maybe instead of `CSP_REPORT_ONLY` `true|false`, change `CSP` to support `true|false|reportOnly` ?

2022-03-07 16:14 UTC, melloware commented
or we could just use 1 param...

```xml
    <context-param>
        <param-name>primefaces.CSP_REPORT_ONLY</param-name>
        <param-value>/csp-reporting</param-value>
    </context-param>
```

basically if the value for REPORT_ONLY exists its considered report only and we use the value as the endpoint?

2022-03-07 16:15 UTC, tandraschko commented
i dont like to introduce 1 param in web.xml for multiple header values (1:N), therefore i would follow `CSP_POLICY`

2022-03-07 16:16 UTC, melloware commented
No problem.  I like your idea then of `CSP` being a value.

2022-03-08 05:07 UTC, cnsgithub commented
> and maybe instead of `CSP_REPORT_ONLY` `true|false`, change `CSP` to support `true|false|reportOnly` ?

The disadvantage of this would be that CSP cannot be turned on together with reporting?

Where do you want to specify the `report-uri`? In both `CSP_POLICY_REPORT_ONLY ` and `CSP_POLICY`?

2022-03-08 08:26 UTC, tandraschko commented
hmmmm, ok we have 4 possible modes now:
- CSP off (CSP=false)
- CSP on (CSP=true)
- CSP on with reporting (CSP=true, CSP_POLICY=report-uri /csp-violation-report-endpoint/)
- CSP off but reporting only

so the 4) is the only new mode now
and i think `CSP_REPORT_ONLY` and `CSP_REPORT_ONLY_POLICY=report-uri /csp-violation-report-endpoint/` is fine

2022-03-18 13:09 UTC, tandraschko commented
any update?

2022-03-28 14:22 UTC, christophs78 commented
MDN says report-uri is deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

2022-03-29 04:30 UTC, cnsgithub commented
> MDN says report-uri is deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

That's true in theory but not in practice since not all browsers support the new `Report-To` header: https://caniuse.com/?search=report-to

![grafik](https://user-images.githubusercontent.com/13161711/160533490-409f4a81-9465-45f5-9550-2f344f45d9de.png)

2022-03-29 04:31 UTC, cnsgithub commented
> any update?

Sorry, currently no time, maybe someone else wants to take over, otherwise we would have to wait for a while.

2022-03-29 08:46 UTC, tandraschko commented
then i will close it for now

2022-03-29 08:46 UTC, closed without merging