Fixes #8977 - DataExporter: Numbers greater than 1000 are formatted as currency in Excel exporter with numberConverter
primefaces/primefaces pull request #8980
Opened 2022-07-08 22:08 UTC by jasonex7

Fixes #8977

This modifies #8964 by changing the name of the property decimalFormat to more specific name "currencyFormat"

2022-07-09 11:35 UTC, melloware requested changes

2022-07-09 11:35 UTC, melloware commented on primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java
> +    private boolean setNumberValueIfApropiate(Cell cell, String value) {
Appropriate has two P's.

2022-07-10 00:17 UTC, jasonex7 commented on primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java
> +    private boolean setNumberValueIfApropiate(Cell cell, String value) {
Oh, I fix the typo

2022-07-10 00:57 UTC, melloware approved these changes

2022-07-10 00:57 UTC, merged