#9629 SelectOneMenu: filter does not work for lowercase i character
primefaces/primefaces pull request #9630
Opened 2023-01-10 18:41 UTC by jepsar

Fix #9629

If this is okay, we can add the normalize function to other components with search filters.

Can be tested at http://localhost:8080/showcase/ui/input/oneMenu.xhtml and search at "Advanced" on "curac" to find "Curaçao".

2023-01-10 18:48 UTC, melloware approved these changes
This looks fantastic!   Did you check if we have any other places we might need this?

2023-01-10 18:52 UTC, melloware commented
Damn build is getting `JSC_UNTRANSPILABLE. Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language. `   Althought now that we have dropped IE support I wonder if we can bump up the transpiler?

here is the browsers supporting it: https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes

2023-01-10 19:01 UTC, jepsar commented
> Damn build is getting `JSC_UNTRANSPILABLE. Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language. ` Althought now that we have dropped IE support I wonder if we can bump up the transpiler?
> 
> here is the browsers supporting it: https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes

Was just looking at it. I refactored it.

2023-01-10 19:13 UTC, jepsar commented
> This looks fantastic! Did you check if we have any other places we might need this?

I think these components:

* SelectOneListbox
* SelectManyMenu
* SplitButton
* PickList
* Tree
* TreeTable
* DataTable

2023-01-10 19:45 UTC, melloware approved these changes

2023-01-10 19:47 UTC, melloware requested changes

2023-01-10 19:47 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
> +        normalize: function(string, lowercase) {
`if (!string) return string;`

2023-01-10 19:48 UTC, melloware commented
On more change I think since it a util function you should defend against NPE of someone passing in `undefined` or NULL string

2023-01-10 19:49 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
> +                itemLabel = PrimeFaces.normalize(option.text(), !this.cfg.caseSensitive)
missing comma after this line?

2023-01-10 20:00 UTC, melloware commented
Sorry if I stole your thunder too I answered on Stack Overflow even though that question was 7 years old.

2023-01-10 20:12 UTC, jepsar commented
> Sorry if I stole your thunder too I answered on Stack Overflow even though that question was 7 years old.

No problem! Upvoted.

2023-01-10 20:13 UTC, melloware approved these changes

2023-01-10 21:34 UTC, merged

2023-01-11 08:22 UTC, jepsar commented
> > This looks fantastic! Did you check if we have any other places we might need this?
> 
> I think these components:
> 
> * SelectOneListbox
> * SelectManyMenu
> * SplitButton
> * PickList
> * Tree
> * TreeTable
> * DataTable

I'll go over these components this evening to see if / how we can add normalization there.