#9989 AutoComplete: Accessibility
primefaces/primefaces pull request #9994
Opened 2023-04-04 20:41 UTC by christophs78

2023-04-26 16:59 UTC, christophs78 commented
We internally backported this to a older PrimeFaces version and deployed it into a live-project. My disabled colleague using JAWS is happy.

2023-04-26 18:05 UTC, melloware approved these changes

2023-04-26 18:48 UTC, melloware requested changes

2023-04-26 18:48 UTC, melloware commented on primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +        this.input.attr('aria-activedescendant', itemId);
```suggestion
        if (item) {
           this.input.attr('aria-activedescendant', item.id);
        }     
```

2023-04-28 18:23 UTC, christophs78 commented on primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
> +        this.input.attr('aria-activedescendant', itemId);
good point!

2023-04-28 18:37 UTC, melloware approved these changes

2023-04-28 19:36 UTC, merged